//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1.Areas.Quanly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIACHICHITIET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIACHICHITIET()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public string MaDC { get; set; }
        public int SDT { get; set; }
        public string Tenduong { get; set; }
        public string Sonha { get; set; }
        public string Tenphuong { get; set; }
        public string Xa { get; set; }
        public string Tinh { get; set; }
        public string Thanhpho { get; set; }
        public string Quan { get; set; }
        public string Huyen { get; set; }
        public string Hotennguoinhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
