//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1.Areas.Quanly.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MotaSP { get; set; }
        public double GiaSP { get; set; }
        public string MaTH { get; set; }
        public string MaDM { get; set; }
        public double SoluongSP { get; set; }
        public Nullable<double> SoluongtonSP { get; set; }
        public string TrangthaiSP { get; set; }
        public string MaDT { get; set; }
        public string ThongtinSP { get; set; }
        public string Vandeveda { get; set; }
        public string Uuthenoibac { get; set; }
        public string Hieuquasudung { get; set; }
        public string Baoquan { get; set; }
        public string ThanhphanSP { get; set; }
        public string Huongdansudung { get; set; }
        public string HA { get; set; }
    
        public virtual CHITIETHINHANH CHITIETHINHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual DUNGTICH DUNGTICH { get; set; }
        public virtual GIOHANG GIOHANG { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
